inherit_from:
  - .rubocop_todo.yml
  - .rubocop_airbnb.yml

require: rubocop-rspec

Layout/IndentationConsistency:
  Exclude:
    - 'db/migrate/*.rb'

Layout/LeadingCommentSpace:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/LineLength:
  Exclude:
     - 'db/seeds.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Layout/IndentationConsistency:
  Exclude:
    - 'db/migrate/*.rb'

Layout/LeadingCommentSpace:
  Exclude:
    - 'db/migrate/*.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'app/controllers/microposts_controller.rb'
Lint/AssignmentInCondition:
  Exclude:
    - 'app/helpers/sessions_helper.rb'

Metrics/LineLength:
  Max: 132

RedundantSelf:
  Enabled: false

Airbnb/ContinuationSlash:
  Exclude:
    - 'spec/spec_helper.rb'

Airbnb/OptArgParameters:
  Exclude:
    - 'app/helpers/application_helper.rb'

Airbnb/SimpleModifierConditional:
  Exclude:
    - 'spec/spec_helper.rb'

Layout/AlignParameters:
  Exclude:
    - 'config/application.rb'

Layout/EmptyLines:
  Exclude:
    - 'config/application.rb'
    - 'spec/spec_helper.rb'

Layout/LeadingCommentSpace:
  Exclude:
    - 'db/migrate/*.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'
