inherit_from:
  - .rubocop_airbnb.yml

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'app/controllers/microposts_controller.rb'
Lint/AssignmentInCondition:
  Exclude:
    - 'app/helpers/sessions_helper.rb'

RedundantSelf:
  Enabled: false
